// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_MapTravelMZ","status":true,"description":"(v.1.1) 地図上の場所を選択して移動できる新しいシーンを作れます","parameters":{"varMap":"1","xVar":"2","yVar":"3","textConfirm":"移動","textCancel":"キャンセル","windowWidth":"180","spriteFrames":"3","frameSpeed":"10"}}
];
